version: "3.8"

services:
  microservice:
    build: ./backend
    container_name: fast-api2
    restart: unless-stopped
    volumes:
      - './backend:/app'
    ports:
      - "8000:8000"
#    depends_on:
#      - redis
    command: uvicorn main:app --host=0.0.0.0 --port=8000 --reload

  redis:
    image: redis:5
    container_name: redis-db
    restart: unless-stopped
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - '6379:6379'
#    command: redis-server /usr/local/etc/redis/redis.conf
    command: redis-server
